### ISSUE TITLE
Should have configuration settings

### ISSUE THREAD

**Issue by sefatanam** [naaive/orange#15]
So that I can,
1. Add exclude path that will be prevented from indexting.*
2. Filter file type*
3. Dark mode ( optional )

Those common settings are missing. Please consider this as a feature request. 
Thanks

**Comment by naaive** [comment]
thanks for your suggestion.
1.  it's more detail setting, will support in future.
2. it's in progress on branch `search_filter`.
3. will be supported.(i am not very good at ui design, so it will cost some time :p)

**Comment by naaive** [comment]
> So that I can,
> 
> 1. Add exclude path that will be prevented from indexting.*
> 2. Filter file type*
> 3. Dark mode ( optional )
> 
> Those common settings are missing. Please consider this as a feature request. Thanks

Hihi, All feature supported except dark theme，have a try！

**Comment by sefatanam** [comment]
hello,

you should make it safe (the latest version ) anyway I installed it & you did awesome! 💥,
thanks a ton.

![image](https://user-images.githubusercontent.com/37630292/161396553-290ae7d2-3136-4f34-9997-5e0c96e620db.png)

**Comment by naaive** [comment]
> hello,
> 
> you should make it safe (the latest version ) anyway I installed it & you did awesome! 💥, thanks a ton.
> 
> ![image](https://user-images.githubusercontent.com/37630292/161396553-290ae7d2-3136-4f34-9997-5e0c96e620db.png)

well noted
