### ISSUE TITLE
安装使用体验

### ISSUE THREAD

**Issue by cream-sec** [naaive/orange#16]
MAC下使用后有以下几个体验：
（1）安装快捷方便，界面简约，很喜欢这点；
（2）电脑插了很多移动硬盘后，做前置缓冲会很慢（文件太多，能理解）；
（3）查询数据显示不完整，很多预期结果没有查询出来（有点难受呀）。

**Comment by naaive** [comment]
感谢反馈！
（2）目前索引速度还有较大提升空间，下个release会有改善；之后也会支持索引指定exclude目录
（3）当前搜索结果限制了只有100条，可能会不全。下个release会有根据文件类型过滤，应该会有一点帮助。

**Comment by naaive** [comment]
已升级，欢迎体验
