### ISSUE TITLE
when open this in windows, throw STATUS_INVALID_IMAGE_HASH

### ISSUE THREAD

**Issue by klren0312** [naaive/orange#5]
![image](https://user-images.githubusercontent.com/10903843/158323135-57818679-2bd9-423c-aca5-72235ba125f8.png)

![image](https://user-images.githubusercontent.com/10903843/158323199-fccb5a75-b4f8-474f-8c52-d6309b927a27.png)

**Comment by naaive** [comment]
I google this err, maybe u could have a try to put `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\RendererCodeIntegrityEnabled =>0 `to registry. 

ref: https://blog.clarence.tw/2020/07/22/status-invalid-image-hash-appears-after-win-10-chrome-and-edge-upgrade/

**Comment by klren0312** [comment]
> I google this err, maybe u could have a try to put `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\RendererCodeIntegrityEnabled =>0 `to registry.
> 
> @klren0312
> 
> ref: https://blog.clarence.tw/2020/07/22/status-invalid-image-hash-appears-after-win-10-chrome-and-edge-upgrade/

not work
![1647394894(1)](https://user-images.githubusercontent.com/10903843/158499910-9fd4d78a-d006-441a-9fc6-cfe87d32fb3a.png)

**Comment by klren0312** [comment]
abandon
