### ISSUE TITLE
您无法打开应用程序“Orange”，因为这台Mac不支持此应用程序。

### ISSUE THREAD

**Issue by zhaojiafu** [naaive/orange#8]
这种怎么解决呀，mac电脑。电脑cpu：双核Intel Core i5

**Comment by naaive** [comment]
试一下Intel版的，https://github.com/naaive/orange/releases/tag/orange-v0.0.6

**Comment by zhaojiafu** [comment]
大佬666，明天到公司了试试

**Comment by leopku** [comment]
> 试一下Intel版的，https://github.com/naaive/orange/releases/tag/orange-v0.0.6

macOS 11.5 可以用了，多谢。

**Comment by zhaojiafu** [comment]
> 试一下Intel版的，https://github.com/naaive/orange/releases/tag/orange-v0.0.6

可以了，666呀
